'use strict';
const DEFAULT_BANK_URL='https://docs.google.com/spreadsheets/d/1m2UBLTw6tiayReLXHKPlhr7bGpgReh41PqvKxIQRmt8/edit#gid=0';
let bankMessage='';
const TEAMS=[{name:'구청장팀',count:16,color:'#66bceb',ink:'#26648a',gradient:'pawnBlue'},{name:'관장팀',count:16,color:'#f2c547',ink:'#705013',gradient:'pawnYellow'},{name:'지회장팀',count:18,color:'#419868',ink:'#296645',gradient:'pawnGreen'}];
const CATS={smart:['스마트','스마트경로당 퀴즈','#9bd7e8','📺'],chuseok:['추석','추석 퀴즈','#f5ab68','🌕'],town:['동네','우리동네 퀴즈','#aad180','🏘️'],memory:['추억','추억 퀴즈','#ffda73','📻'],song:['노래','노래 한 소절','#c8a5e3','♪'],mission:['미션','팀 미션','#f39aad','🙌'],chance:['찬스','복주머니 찬스','#9bbfee','🧧'],special:['특별','특별찬스','#f5a066','🧧'],golden:['골든','골든미션','#ffda61','✨'],cheer:['응원','응원전','#f4aac9','👏']};
const TYPES={'스마트경로당퀴즈':'smart','추석퀴즈':'chuseok','우리동네퀴즈':'town','추억퀴즈':'memory','노래':'song','노래한소절':'song','팀미션':'mission','복주머니찬스':'chance','특별찬스':'special','골든미션':'golden','응원전':'cheer'};
const KEYS={state:'onmaeul.state.v3',bank:'onmaeul.bank.v3',lock:'onmaeul.control.v3',api:'onmaeul.api.v3',history:'onmaeul.history.v3'};
const clone=o=>JSON.parse(JSON.stringify(o)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({version:3,revision:0,players:TEAMS.map(()=>({path:['S']})),scores:[0,0,0],selected:0,screen:'opening',at:Date.now(),phase:'ready',route:'shortcut',busy:false,passed:[],notice:'',card:null,timer:null,scored:false,outcome:null,extra:false,sound:true,cheerTarget:0,cheerWinner:null,cheerAwarded:false,returnScreen:'board',chance:null,chanceApplied:false,turnAt:0,flash:'',flashUntil:0,bank:clone(DEFAULT_BANK),bankAt:null});
let S=fresh(),history=[],authority=false,mode='control',channel=null,storageOK=true,owner='',lastScreen='',lastBank='',lastClock=-1,ctx=null,apiMessage='',fetching=false,displayWindow=null;
const coords={};for(let i=1;i<=24;i++){if(i<=7)coords[i]=[112+(i-1)*1360/6,60];else if(i<=13)coords[i]=[1472,60+(i-7)*92];else if(i<=19)coords[i]=[1472-(i-13)*1360/6,612];else coords[i]=[112,612-(i-19)*92];}Object.assign(coords,{25:[418,184],26:[1166,184],27:[792,336],28:[418,488],29:[1166,488]});
const position=p=>p.path.at(-1),$=id=>document.getElementById(id);
function nextStep(p,first,route='shortcut'){const a=position(p);if(a==='F')return 'F';if(a==='S')return 12;if(a===13)return 'F';if(first&&route==='shortcut'&&a===7)return 26;if(first&&route==='shortcut'&&a===1)return 25;if(a===27)return first?(route==='shortcut'?29:28):(p.path.at(-2)===26?28:29);return ({26:27,25:27,28:19,29:13})[a]||(a===1?24:a-1);}
function canonical(id){if(id==='S')return ['S'];const outer=['S',12,11,10,9,8,7,6,5,4,3,2,1,24,23,22,21,20,19,18,17,16,15,14,13];if(id==='F')return [...outer,'F'];const n=Number(id);if(n<=24)return outer.slice(0,outer.indexOf(n)+1);if(n===26)return [...canonical(7),26];if(n===25)return [...canonical(1),25];if(n===27)return [...canonical(7),26,27];if(n===28)return [...canonical(7),26,27,28];if(n===29)return [...canonical(1),25,27,29];throw Error('칸번호는 1~29입니다.');}
function seconds(t=S.timer,now=Date.now()){if(!t)return 0;return Math.max(0,Math.ceil((t.running?t.deadline-now:t.remaining)/1000));}
function validateBank(rows){if(!Array.isArray(rows)||!rows.length)throw Error('문제 행이 없습니다.');const seen=new Set;return rows.map((raw,index)=>{const korean=Object.hasOwn(raw,'칸번호');const get=(k,en)=>korean?raw[k]:raw[en];const id=Number(get('칸번호','id'));if(!Number.isInteger(id)||id<1||id>29||seen.has(id))throw Error((index+1)+'행: 칸번호는 중복 없이 1~29여야 합니다.');seen.add(id);const val=get('사용여부','enabled');const enabled=val===undefined||val===''?true:val===true||String(val).toUpperCase()==='TRUE';const typ=String(get('유형','type')||'').replace(/\s/g,'');const type=TYPES[typ]||typ;if(!CATS[type])throw Error(id+'번: 유형을 확인하세요.');let choices=korean?[1,2,3,4].map(n=>String(raw['보기'+n]??'').trim()):(raw.choices||[]).map(String);const has=choices.some(Boolean);let answer=get('정답','answer');if(has&&enabled){if(choices.length!==4||choices.some(x=>!x))throw Error(id+'번: 보기 1~4를 모두 입력하세요.');if(/^[1-4]$/.test(String(answer).trim()))answer=choices[Number(answer)-1];if(!choices.includes(String(answer)))throw Error(id+'번: 정답은 1~4 또는 보기 내용이어야 합니다.');}else choices=[];const duration=Number(get('제한시간','duration')||20);if(!Number.isFinite(duration)||duration<5||duration>600)throw Error(id+'번: 제한시간은 5~600초입니다.');const question=String(get('문제','question')||''),title=String(get('제목','title')||CATS[type][1]),prompt=String(get('미션내용','prompt')||'');if(enabled&&choices.length&&!question.trim())throw Error(id+'번: 문제를 입력하세요.');if(enabled&&!choices.length&&!prompt.trim())throw Error(id+'번: 미션내용을 입력하세요.');return {id,type,title,question,prompt,choices,answer:String(answer??''),duration,enabled};});}
function safeRead(key){try{return JSON.parse(localStorage.getItem(key));}catch{return null;}}
function safeWrite(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{storageOK=false;}}
function hasControl(){if(!authority)return false;const lock=safeRead(KEYS.lock);if(storageOK&&lock&&lock.owner!==owner&&Date.now()-lock.at<4500){authority=false;renderControl();return false;}return true;}
function saveHistory(){safeWrite(KEYS.history,history);}
function pushHistory(){const snap=clone(S);if(snap.timer?.running){snap.timer.remaining=Math.max(0,snap.timer.deadline-Date.now());snap.timer.running=false;}history.push(snap);if(history.length>80)history.shift();saveHistory();}
function publish(){S.revision++;safeWrite(KEYS.state,S);channel?.postMessage({kind:'state',state:S});render();}
function setScreen(screen){S.screen=screen;S.at=Date.now();}
function tone(kind){if(!hasControl()||!S.sound)return;try{ctx??=new (window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();const notes={step:[660],intro:[220,330,440],count:[880],end:[440,330],answer:[523,659,784,1047],special:[392,523,659,784],golden:[523,659,784,1047,1319],finish:[523,659,784,1047,784,1047]}[kind]||[660];notes.forEach((hz,i)=>{const start=ctx.currentTime+i*.12,osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=kind==='step'?'sine':'triangle';osc.frequency.setValueAtTime(hz,start);gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.12,start+.01);gain.gain.exponentialRampToValueAtTime(.001,start+.16);osc.connect(gain);gain.connect(ctx.destination);osc.start(start);osc.stop(start+.18);});}catch{/* 음향 실패가 진행을 막지 않습니다. */}}
function startTimer(duration){S.timer={startedAt:Date.now(),duration,remaining:duration*1000,deadline:Date.now()+duration*1000,running:true,ended:false,kind:S.screen==='cheer'?'cheer':'quiz'};lastClock=-1;}
function endTimer(){if(!S.timer||S.timer.ended)return;S.timer.running=false;S.timer.remaining=0;S.timer.ended=true;tone('end');if(S.timer.kind==='quiz'){setScreen('camera');S.cameraUntil=Date.now()+3000;}}
function timerAction(action){if(!S.timer)return;const t=S.timer;if(action==='pause'){t.remaining=Math.max(0,t.deadline-Date.now());t.running=false;}if(action==='start'&&!t.ended){t.deadline=Date.now()+t.remaining;t.running=true;}if(action==='restart'){const duration=t.duration;S.screen=t.kind==='quiz'?'question':'cheer';startTimer(duration);}if(action==='add'){t.remaining=(t.running?Math.max(0,t.deadline-Date.now()):t.remaining)+10000;t.duration=Math.max(t.duration,t.remaining/1000);t.deadline=Date.now()+t.remaining;t.ended=false;if(S.screen==='camera')S.screen='question';}if(action==='end')endTimer();publish();}
async function roll(steps,correction=false){if(!hasControl()||S.busy||(!correction&&(S.screen!=='board'||!['ready','extra'].includes(S.phase))))return;const p=S.players[S.selected];if(steps>0&&position(p)==='F'||steps<0&&p.path.length<2)return;pushHistory();S.busy=true;S.card=null;S.passed=[];S.notice='';if(!correction&&steps>=4){S.flash=steps===4?'윷 나왔습니다!':'모! 복 터졌습니다!';S.flashUntil=Date.now()+1200;tone('special');}publish();if(steps>=4&&!correction)await new Promise(r=>setTimeout(r,900));for(let i=0;i<Math.abs(steps);i++){if(!hasControl())return;if(steps<0)p.path.pop();else p.path.push(nextStep(p,i===0,S.route));S.passed.push(position(p));tone('step');publish();await new Promise(r=>setTimeout(r,460));if(position(p)==='F')break;}if(!hasControl())return;S.busy=false;S.route='shortcut';const at=position(p);if(correction){S.phase=at==='F'?'finished':'ready';S.notice='';publish();return;}let caught=false;if(at!=='F'){S.players.forEach((other,i)=>{if(i!==S.selected&&position(other)===at){other.path=['S'];caught=true;}});}S.extra=(steps>=4||caught)&&at!=='F';S.phase=S.extra?'extra':'next';S.notice=caught?'잡았습니다! 한 번 더!':S.extra?'한 번 더! 복이 이어집니다!':'도착!';if(at==='F'){S.phase='finished';S.notice=TEAMS[S.selected].name+' 완주!';tone('finish');publish();return;}S.card=clone(S.bank.find(c=>c.id===at&&c.enabled)||null);S.scored=false;S.outcome=null;S.timer=null;S.chance=null;S.chanceApplied=false;S.flash='도착!';S.flashUntil=Date.now()+700;publish();await new Promise(r=>setTimeout(r,650));if(!hasControl())return;if(S.card){setScreen('intro');tone(S.card.type==='golden'?'golden':'intro');}publish();}
function openContent(){if(!S.card)return;S.flash='';if(S.card.type==='cheer'){startCheer(true);return;}if(S.card.type==='special'){setScreen('chance');tone('special');return;}if(S.card.choices?.length){setScreen('question');startTimer(S.card.duration||20);}else{setScreen('mission');S.timer=null;if(S.card.type==='golden')tone('golden');}publish();}
function startCheer(fromCell=false){S.returnScreen=fromCell?'board':S.screen;S.cheerTarget=S.selected;S.cheerWinner=null;S.cheerAwarded=false;setScreen('cheer');startTimer(10);publish();}
function parseChance(card){const prompt=card?.prompt||'';const points=prompt.match(/\[점수:(-?\d+)\]/);if(points)return {type:'points',value:Number(points[1]),label:'+'+Number(points[1])+'점',text:prompt.replace(points[0],'').trim()};if(prompt.includes('[한번더]'))return {type:'extra',label:'한 번 더!',text:prompt.replace('[한번더]','').trim()};if(prompt.includes('[보너스]'))return {type:'bonus',label:'보너스 문제',text:prompt.replace('[보너스]','').trim()};return {type:'gift',label:'전체 경로당 선물찬스',text:prompt.replace('[선물]','').trim()};}
function revealChance(){if(S.chanceApplied)return;pushHistory();S.chance=parseChance(S.card);S.chanceApplied=true;if(S.chance.type==='points')S.scores[S.selected]+=S.chance.value;if(S.chance.type==='extra'){S.extra=true;S.phase='extra';S.notice='특별찬스! 한 번 더!';}S.at=Date.now();tone('special');publish();}
function finishContent(){S.timer=null;if(S.screen==='chance'&&S.chance?.type==='bonus'){const bonus=S.bank.find(c=>c.enabled&&c.choices?.length&&c.id!==S.card?.id);if(bonus){S.card=clone(bonus);S.scored=false;S.outcome=null;setScreen('intro');publish();return;}}setScreen('board');S.card=null;S.outcome=null;S.notice=S.extra?'한 번 더! '+TEAMS[S.selected].name+'의 기회!':'';publish();}
function applyScore(success){if(S.scored)return;pushHistory();S.scored=true;S.outcome=success?'success':'soft';if(success){if(S.card?.type==='golden')S.scores=S.scores.map(n=>n+1);else S.scores[S.selected]++;tone('answer');}S.at=Date.now();publish();}
function dispatch(action,value){if(!hasControl()||S.busy&&action!=='sound')return;if(action==='roll'){roll(Number(value));return;}if(action==='forward'||action==='back'){roll(action==='forward'?1:-1,true);return;}if(action.startsWith('timer-')){timerAction(action.slice(6));return;}switch(action){case 'opening':pushHistory();S.timer=null;setScreen('opening');break;case 'skip':setScreen('board');break;case 'team':pushHistory();S.selected=Number(value);S.route='shortcut';S.extra=false;S.phase=position(S.players[S.selected])==='F'?'finished':'ready';S.card=null;S.timer=null;S.notice='';setScreen('board');S.turnAt=Date.now();break;case 'route':S.route=value;break;case 'next':if(S.extra)return;{const next=[1,2,3].map(n=>(S.selected+n)%3).find(i=>position(S.players[i])!=='F');if(next===undefined)return;pushHistory();S.selected=next;S.phase='ready';S.route='shortcut';S.notice='';S.turnAt=Date.now();S.card=null;S.timer=null;setScreen('board');}break;case 'open':openContent();return;case 'answer':if(!S.timer?.ended)return;setScreen('answer');tone('answer');break;case 'complete':finishContent();return;case 'good':applyScore(true);return;case 'soft':applyScore(false);return;case 'undo':if(!history.length)return;{const before=history.pop();before.revision=S.revision;S=before;S.busy=false;S.flash='';if(S.screen==='camera')S.screen='question';saveHistory();}break;case 'position':pushHistory();S.players[S.selected].path=canonical(value);S.phase=value==='F'?'finished':'ready';S.extra=false;S.card=null;S.timer=null;S.notice='';setScreen('board');break;case 'sound':S.sound=!S.sound;if(S.sound)tone('step');break;case 'cheer':pushHistory();startCheer();return;case 'cheertarget':S.cheerTarget=Number(value);break;case 'cheerwinner':if(!S.timer?.ended||S.cheerAwarded)return;pushHistory();S.cheerWinner=Number(value);S.scores[S.cheerWinner]+=2;S.cheerAwarded=true;S.at=Date.now();tone('answer');break;case 'cheerdone':S.timer=null;setScreen('board');break;case 'standings':pushHistory();S.returnScreen=S.screen;setScreen('standings');break;case 'bumper':pushHistory();S.returnScreen=S.screen;setScreen('bumper');break;case 'chance':revealChance();return;case 'finale':if(!confirm('현재 점수로 우승팀을 발표하고 피날레를 시작할까요?'))return;pushHistory();S.timer=null;setScreen('finale');tone('finish');break;case 'score':{const parts=value.split(':');const team=Number(parts[0]),score=Number(parts[1]);if(!Number.isFinite(score)||Math.abs(score)>9999)return;pushHistory();S.scores[team]=score;}break;case 'reset':if(!confirm('모든 말과 점수를 초기화할까요? 문제은행은 유지됩니다.'))return;{const bank=S.bank,bankAt=S.bankAt,sound=S.sound;S=fresh();S.bank=bank;S.bankAt=bankAt;S.sound=sound;history=[];saveHistory();}break;case 'board':S.timer=null;setScreen('board');break;default:return;}publish();}
function bankRequestUrl(value){
  const url=new URL(value);
  if(url.protocol!=='https:'||url.username||url.password)throw Error('구글시트 또는 Apps Script의 HTTPS 주소를 입력하세요.');
  const sheet=url.pathname.match(/^\/spreadsheets\/d\/([\w-]+)\/(?:edit|export)?$/);
  if(url.hostname==='docs.google.com'&&sheet){
    const gid=url.searchParams.get('gid')||new URLSearchParams(url.hash.slice(1)).get('gid')||'0';
    if(!/^\d+$/.test(gid))throw Error('시트 탭 번호(gid)를 확인하세요.');
    return {url:`https://docs.google.com/spreadsheets/d/${sheet[1]}/export?format=csv&gid=${gid}`,csv:true};
  }
  if(url.hostname==='script.google.com'&&/^\/macros\/s\/[^/]+\/exec$/.test(url.pathname))return {url:url.href,csv:false};
  throw Error('구글시트 공유 주소 또는 Apps Script의 /exec 주소를 입력하세요.');
}
function parseBankCsv(text){
  const table=[];let row=[],cell='',quoted=false;
  text=text.replace(/^\uFEFF/,'');
  for(let i=0;i<text.length;i++){
    const c=text[i];
    if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}
    else if(c===','&&!quoted){row.push(cell);cell='';}
    else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))table.push(row);row=[];cell='';}
    else cell+=c;
  }
  if(quoted)throw Error('시트 CSV의 따옴표가 닫히지 않았습니다.');
  row.push(cell);if(row.some(v=>v.trim()))table.push(row);
  const headers=(table.shift()||[]).map(v=>v.trim());
  const required=['칸번호','유형','제목','문제','보기1','보기2','보기3','보기4','정답','미션내용','제한시간','사용여부'];
  for(const name of required)if(!headers.includes(name))throw Error('문제은행 시트의 필수 열이 없습니다: '+name);
  return table.filter(r=>r[headers.indexOf('칸번호')]?.trim()).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));
}
async function refreshBank(){
  if(fetching||S.busy||!hasControl())return;
  if(!['board','opening'].includes(S.screen)){bankMessage='문제 진행을 마친 뒤 윷판에서 새로고침해 주세요.';renderControl();return;}
  const source=$('apiUrl').value.trim();let request;
  try{request=bankRequestUrl(source);}catch(error){bankMessage=error.message;renderControl();return;}
  fetching=true;bankMessage='문제은행을 불러오고 있습니다…';renderControl();
  const abort=new AbortController(),timeout=setTimeout(()=>abort.abort(),30000);
  try{
    const url=new URL(request.url);url.searchParams.set('t',Date.now());
    const response=await fetch(url,{signal:abort.signal,redirect:'follow',cache:'no-store',credentials:'omit'});
    if(!response.ok)throw Error('시트 열람 권한 또는 웹앱 배포 권한을 확인하세요. (응답 '+response.status+')');
    const text=await response.text();
    if(/^\s*</.test(text))throw Error('문제 데이터 대신 로그인·오류 화면을 받았습니다. 시트 열람 권한 또는 Apps Script 배포 권한을 확인하세요.');
    const payload=request.csv?parseBankCsv(text):JSON.parse(text);
    if(payload.error)throw Error(payload.error);
    const rows=validateBank(payload.rows||payload);
    if(!hasControl())throw Error('조작권이 변경되었습니다. 조작권을 이어받은 뒤 다시 불러오세요.');
    pushHistory();const byId=new Map(rows.map(r=>[r.id,r]));
    S.bank=DEFAULT_BANK.map(c=>byId.get(c.id)||{...clone(c),enabled:false});
    S.bankAt=Date.now();S.bankSource=source;
    safeWrite(KEYS.api,source);safeWrite(KEYS.bank,{rows:S.bank,at:S.bankAt});
    bankMessage=rows.filter(r=>r.enabled).length+'개 문제·미션 불러옴 · 서버 저장 중…';
    await publish();
    bankMessage=hasControl()?rows.filter(r=>r.enabled).length+'개 문제·미션 반영 완료':'문제를 불러왔으나 서버 저장을 확인하지 못했습니다. 연결과 조작권을 확인하세요.';
  }catch(error){bankMessage='새 문제 반영에 실패했습니다. '+(error.name==='AbortError'?'응답 시간이 초과되었습니다. 잠시 후 다시 시도하세요.':error.message);}
  finally{clearTimeout(timeout);fetching=false;renderControl();}
}

function confetti(){return '<div class="celebrate">'+Array.from({length:45},(_,i)=>`<i class="confetti" style="--x:${(i*37)%100}%;--c:${['#e99038','#ec819c','#80af66','#79afe2','#f5ce43'][i%5]};--delay:${i%7*.12}s"></i>`).join('')+'</div>';}
function lights(heart=false){return `<div class="${heart?'heart-lights':'dotring'}">`+Array.from({length:50},(_,i)=>{const t=i/50*Math.PI*2;const x=heart?300+16*Math.pow(Math.sin(t),3)*16:742+645*Math.cos(t);const y=heart?215-(13*Math.cos(t)-5*Math.cos(2*t)-2*Math.cos(3*t)-Math.cos(4*t))*14:330+285*Math.sin(t);return `<i class="light" style="left:${x}px;top:${y}px;--delay:${i*.035}s"></i>`;}).join('')+'</div>';}
function audience(){const team=TEAMS[S.selected];return `<p class="challenge">지금은 ${team.name} ${team.count}개 경로당이 도전합니다!</p><p class="support">${TEAMS.filter((_,i)=>i!==S.selected).map(t=>t.name).join('·')}은 응원해주세요!</p>`;}
function showHTML(){const card=S.card,cat=CATS[card?.type]||CATS.chuseok;const wrap=(content,cls='')=>`<section class="show ${cls}">${content}</section>`;const icon=`<span class="typeicon ${card?.type==='song'?'song-icon':card?.type==='special'?'special-icon':''}">${cat[3]}</span>`;if(S.screen==='board')return '';if(S.screen==='opening'){return wrap(`<p class="kicker">동백꽃노인종합복지관 × 스마트경로당 50개소</p><h2 class="big">온(ON)마을 복(福) 터졌네!</h2><h3>2026 스마트경로당 한가위 골든벨</h3><div class="network"><svg class="net-lines" viewBox="0 0 860 265">${Array.from({length:10},(_,i)=>{const x=i<5?50+i*190:50+(i-5)*190,y=i<5?20:210;return `<path d="M430 125 Q${x} 125 ${x} ${y}"/>`;}).join('')}</svg><div class="hub">동백꽃 복지관<small>스튜디오 ON</small></div>${Array.from({length:10},(_,i)=>`<span class="home-icon" data-home="${i}" style="--x:${i<5?30+i*190:30+(i-5)*190}px;--y:${i<5?0:205}px">🏠</span>`).join('')}</div><p class="subtitle">동대문구 스마트경로당 <b>50개소</b> 연결 중…</p><p class="connect" id="connectCount"></p><h3 id="onVillage">우리 동네가 하나로 ON!</h3>`,'fullscreen opening');}
if(S.screen==='intro'){return wrap(`<p class="kicker">${card.id}번 칸 도착!</p>${icon}<div><span class="typepill" style="--cat:${cat[2]}">${cat[1]}</span></div><h2 class="intro-title">${(card.choices?.length||card.isQuiz)?'문제가 도착했습니다!':card.type==='golden'?'골든미션!':'복이 찾아왔습니다!'}</h2><p class="subtitle">${card.type==='golden'?'50개 스마트경로당 모두 함께합니다!':(card.choices?.length||card.isQuiz)?'문제를 풀어보세요!':'함께 웃고, 함께 도전해요!'}</p>`,card.type==='golden'?'gold':'');}
if(['question','camera'].includes(S.screen)){return wrap(`${audience()}<h2 class="question">${esc(card.question||card.title)}</h2><div class="choices">${card.choices.map((c,i)=>`<div class="choice">${['①','②','③','④'][i]} ${esc(c)}</div>`).join('')}</div><div class="timer" data-timer></div><p class="write" id="writePrompt">✏️ 정답을 적어주세요!</p><p class="write-sub">${TEAMS[S.selected].name} 경로당만 ① ② ③ ④ 중 하나를 크게 적어주세요!</p><p class="write-sub">작성한 정답판을 카메라에 보여주세요!</p>${S.screen==='camera'?'<div class="camera"><div class="icon">📸</div><div class="camcount" id="camcount"></div><h2>하나, 둘, 셋!<br>정답판 보여주세요!</h2></div>':''}`);}
if(S.screen==='answer'){const num=card.choices.indexOf(card.answer)+1;return wrap(`${audience()}<p class="typepill" style="--cat:${cat[2]}">${cat[1]}</p><div class="answer-main">정답은 ${['①','②','③','④'][num-1]||num}번입니다!</div><div class="answer-value">${esc(card.answer)}</div>${S.outcome?`<p class="stamp">${S.outcome==='success'?'정답입니다! +1점':'아쉽습니다! 정답을 확인해볼까요?'}</p>`:'<p class="subtitle">정답판을 확인해주세요!</p>'}${confetti()}`);}
if(S.screen==='mission'){const all=card.type==='golden';return wrap(`${all?lights():audience()}<div class="${all?'mission-center':''}"><p class="typepill" style="--cat:${cat[2]}">${cat[1]}</p><h2>${all?'50개 스마트경로당 모두 도전!':esc(card.title)}</h2><p class="mission">${esc(card.prompt)}</p>${S.outcome?`<p class="stamp">${S.outcome==='success'?'미션 성공! +1점':'함께 도전해주셔서 감사합니다!'}</p>`:''}</div>${all||S.outcome==='success'?confetti():''}`,all?'fullscreen gold':'');}
if(S.screen==='chance'){return wrap(`<p class="kicker">${card.id}번 특별찬스</p><span class="typeicon special-icon" style="font-size:140px">🧧</span><h2>${S.chance?esc(S.chance.label):'복이 터졌습니다!'}</h2><p class="subtitle">${S.chance?esc(S.chance.text):'어떤 복이 숨어 있을까요?'}</p>${S.chance?confetti():''}`,'gold');}
if(S.screen==='cheer'){return wrap(`<h2>${S.cheerWinner===null?'응원전 START!':'오늘의 응원왕!'}</h2><div class="cheer-teams">${TEAMS.map((t,i)=>`<div class="cheer-team ${S.cheerTarget===i?'target':''} ${S.cheerWinner===i?'winner':''}" style="--team:${t.color};--team-ink:${t.ink}">👏<br>${t.name}${S.cheerWinner===i?'<br><span class="big">+2점</span>':''}</div>`).join('')}</div>${S.cheerWinner===null?'<div class="big" data-timer></div>':''}<p class="subtitle">카메라를 향해 크게 응원해주세요!</p><h3>우리 팀을 힘차게 응원해주세요!</h3>${S.cheerWinner!==null?confetti():''}`,'cheer');}
if(S.screen==='standings'){return wrap(`<h2>한가위 골든벨 현재 현황</h2><div class="rankings">${TEAMS.map((t,i)=>`<div class="ranking" style="--team:${t.color};--team-ink:${t.ink}">${t.name}<strong>${S.scores[i]}점</strong><small>${position(S.players[i])==='S'?'출발':position(S.players[i])==='F'?'완주!':position(S.players[i])+'번 칸'}</small></div>`).join('')}</div><p class="subtitle" style="margin-top:65px">함께하는 도전, 모두에게 큰 박수!</p>`);}
if(S.screen==='bumper'){return wrap(`${lights()}<div class="mission-center"><h2 class="big">50개소 모두 함께!</h2><p class="subtitle">동대문구 스마트경로당 연결 ON!</p><h3>우리 동네가 하나로 ON!</h3></div>`,'fullscreen gold');}
if(S.screen==='finale'){const max=Math.max(...S.scores),winners=TEAMS.filter((_,i)=>S.scores[i]===max);return wrap(`<p class="kicker">오늘의 스마트 한가위 골든벨 결과!</p><div id="winnerView"><h2 class="big">${winners.length>1?'공동 우승!':'우승!'}<br>${winners.map(t=>t.name).join(' · ')}</h2><h3>${max}점 · 축하합니다!</h3>${confetti()}</div><div id="finalThanks" hidden>${lights(true)}<h2>우리 동네가 하나로 ON!</h2><p class="final-message">50개 스마트경로당이 함께해서<br>더욱 즐거운 한가위였습니다.<br>풍성하고 건강한 한가위 보내세요!</p></div>`,'fullscreen gold');}return '';}
function renderBoard(){const bankKey=JSON.stringify(S.bank.map(c=>[c.id,c.type,c.enabled]));if(bankKey!==lastBank){lastBank=bankKey;$('nodes').innerHTML=S.bank.map(cell=>{const [x,y]=coords[cell.id],cat=CATS[cell.type],r=cell.id===27?110:cell.id<=24&&(cell.id>=7&&cell.id<=13||cell.id>=19||cell.id===1)?44:50;return `<g class="node" id="node${cell.id}" transform="translate(${x} ${y})" style="--fill:${cell.enabled?cat[2]:'#e7ddc9'};--text:#493522"><g class="cell-core" id="core${cell.id}"><circle r="${r}" ${cell.id===27?'class="gold-moon" style="fill:url(#gold)"':''}/><text class="num" y="${cell.id===27?-3:8}" style="${cell.id===27?'font-size:90px':''}">${cell.id}</text><text class="label" y="${cell.id===27?43:30}" style="${cell.id===27?'font-size:35px':''}">${cell.id===27?'골든미션':cell.enabled?cat[0]:'쉼터'}</text></g></g>`;}).join('');}
if(!$('pawns').children.length){$('pawns').innerHTML=TEAMS.map((t,i)=>`<g class="pawn" id="pawn${i}"><g class="pawn-size" transform="scale(1.4)"><g class="body"><path d="M-12 -33C-12 -20 -23 -16 -24 -4Q-25 9 0 10Q25 9 24 -4C23 -16 12 -20 12 -33Z" fill="url(#${t.gradient})" stroke="white" stroke-width="3"/><circle cy="-39" r="18" fill="url(#${t.gradient})" stroke="white" stroke-width="3"/><ellipse cx="-6" cy="-45" rx="5" ry="4" fill="#fffb"/><text y="0" style="fill:${i===1?'#533d0f':'#ffffff'}">${i+1}</text></g></g></g>`).join('');}
S.players.forEach((p,i)=>{const at=position(p),group=S.players.map((q,j)=>position(q)===at?j:-1).filter(j=>j!==-1);let [x,y]=at==='F'?[620+i*160,647]:coords[at==='S'?13:at];if(at!=='F'){x+=(group.indexOf(i)-(group.length-1)/2)*74+(at==='S'?-55:20);y+=at==='S'?-7:22;x=Math.max(55,Math.min(1520,x));}if(at==='S'){x=1120+i*85;y=719;}const pawn=$('pawn'+i),xy=`translate(${x} ${y})`;if(pawn.getAttribute('transform')!==xy){pawn.classList.remove('hopping');void pawn.getBoundingClientRect();pawn.classList.add('hopping');pawn.setAttribute('transform',xy);}pawn.classList.toggle('current',S.selected===i);pawn.classList.toggle('arrived',!S.busy&&S.passed.at(-1)===at&&S.selected===i);});
S.bank.forEach(c=>{$('node'+c.id).classList.toggle('passed',S.passed.includes(c.id));$('core'+c.id).classList.toggle('arrival',!S.busy&&S.passed.at(-1)===c.id);});const p=S.players[S.selected],at=position(p);if(S.screen==='board'&&!S.busy&&at!=='F'){const next=nextStep(p,true,S.route),a=coords[at==='S'?13:at],b=coords[next];$('routeglow').setAttribute('d',b?`M${a[0]} ${a[1]}L${b[0]} ${b[1]}`:'');}else $('routeglow').setAttribute('d','');$('boardNote').textContent=S.notice;$('boardwrap').classList.toggle('dim',S.screen!=='board');$('boardwrap').classList.toggle('gone',['opening','bumper','finale'].includes(S.screen)||S.screen==='mission'&&S.card?.type==='golden');}
function button(label,action,value='',disabled=false,css=''){return `<button class="${css}" data-action="${action}" data-value="${esc(value)}" ${disabled?'disabled':''}>${label}</button>`;}
function renderControl(){if(mode==='display')return;const t=TEAMS[S.selected],active=['question','camera'].includes(S.screen),board=S.screen==='board',canRoll=board&&['ready','extra'].includes(S.phase)&&position(S.players[S.selected])!=='F',locked=S.busy;const keep=$('control').scrollTop;const api=$('apiUrl')?.value??S.bankSource??safeRead(KEYS.api)??DEFAULT_BANK_URL;const openDetails=[...document.querySelectorAll('#control details[open]')].map(d=>d.id);
$('control').innerHTML=`<h1>온마을 복 터졌네!</h1><p>진행자 화면 · 방송에는 버튼이 나오지 않습니다.</p><div class="headerbuttons">${button('방송창 열기','display','','','primary')}${button(S.sound?'효과음 ON':'효과음 OFF','sound')}</div>${!authority?`<p class="status">다른 진행자 창이 조작 중입니다.</p>${button('이 창에서 이어서 진행','takeover')}`:''}${!storageOK?'<p class="storage-warning">브라우저 저장 공간을 사용할 수 없습니다. 이 창을 유지하세요.</p>':''}<div class="status">${t.name} · ${esc({opening:'오프닝',board:'윷놀이판',intro:'칸 등장',question:'답안 작성',camera:'정답판 확인',answer:'정답 공개',mission:'미션',chance:'특별찬스',cheer:'응원전',standings:'현재 현황',bumper:'전체 함께',finale:'피날레'}[S.screen]||S.screen)}</div>
${S.screen==='opening'?`<div class="row">${button('오프닝 다시','opening')}${button('윷판으로','skip','','','primary')}</div>`:''}
<h2>현재 팀 / 윷 결과</h2><div class="row">${TEAMS.map((team,i)=>button(team.name,'team',i,locked)).join('')}</div><div class="row">${['도','개','걸','윷','모'].map((n,i)=>button(n+' '+(i+1),'roll',i+1,!canRoll||locked,'accent')).join('')}</div>
${board&&[7,1,27].includes(position(S.players[S.selected]))?`<label>다음 이동 경로</label><div class="row">${button((S.route==='shortcut'?'✓ ':'')+(position(S.players[S.selected])===27?'출발 쪽':'가운데 지름길'),'route','shortcut',locked)}${button((S.route==='outer'?'✓ ':'')+(position(S.players[S.selected])===27?'왼쪽 아래':'바깥길'),'route','outer',locked)}</div>`:''}
<div class="row">${button(S.extra?'한 번 더!': '다음 팀 →','next','',!board||S.extra||locked||S.players.every(p=>position(p)==='F'),'primary')}${button('↶ 실행취소','undo','',!history.length||locked)}</div>
${S.screen==='intro'?`<div class="row">${button(S.card?.choices?.length?'문제 열기':'미션·찬스 열기','open','',false,'accent')}</div>`:''}
${active?`<h2>답안 작성 타이머 <span class="controltime" data-timer></span>초</h2><div class="row">${button('시작','timer-start','',S.timer?.running||S.timer?.ended)}${button('일시정지','timer-pause','',!S.timer?.running)}${button('다시 시작','timer-restart')}</div><div class="row">${button('+10초','timer-add')}${button('즉시 종료','timer-end','',S.timer?.ended)}</div><div class="row">${button('정답 공개','answer','',!S.timer?.ended||S.screen==='camera','accent')}</div>`:''}
${['answer','mission'].includes(S.screen)?`<div class="row">${button(S.screen==='answer'?'정답 +1점':'미션 성공 +1점','good','',S.scored,'primary')}${button('아쉬워요 · 0점','soft','',S.scored)}</div><div class="row">${button(S.screen==='mission'?'미션 완료':'다음 진행','complete','',false,'accent')}</div>`:''}
${S.screen==='chance'?`<div class="row">${button('복주머니 열기','chance','',S.chanceApplied,'accent')}${button('다음 진행','complete','',!S.chanceApplied,'primary')}</div>`:''}
${S.screen==='cheer'?`<h2>응원할 팀 <span data-timer></span>초</h2><div class="row">${TEAMS.map((t,i)=>button(t.name,'cheertarget',i,S.cheerAwarded)).join('')}</div><div class="row">${button('10초 다시','timer-restart')}${button('응원 종료','timer-end','',S.timer?.ended)}</div><h2>오늘의 응원왕 +2점</h2><div class="row">${TEAMS.map((t,i)=>button(t.name,'cheerwinner',i,!S.timer?.ended||S.cheerAwarded)).join('')}</div>${button('윷판으로','cheerdone','','','primary')}`:''}
<h2>방송 연출</h2><div class="row">${button('응원전','cheer','',!board||locked)}${button('현재 현황','standings','',!board||locked)}${button('50개소 함께','bumper','',!board||locked)}</div><div class="row">${button('오프닝','opening','',locked||!board)}${button('피날레','finale','',locked||!board)}${button('윷판 복귀','board','',locked||board)}</div>
<details id="adjustDetails"><summary>말 위치와 점수 수정</summary><div class="row">${button('한 칸 앞으로','forward','',!board||locked||position(S.players[S.selected])==='F')}${button('한 칸 뒤로','back','',!board||locked||S.players[S.selected].path.length<2)}</div><label>현재 팀의 말 위치</label><select id="positionInput"><option value="S">출발</option>${S.bank.map(c=>`<option value="${c.id}">${c.id}번 · ${CATS[c.type][1]}</option>`).join('')}<option value="F">완주</option></select>${button('선택한 위치로 수정','applyPosition','',locked||!board)}<h2>점수 직접 입력</h2>${TEAMS.map((t,i)=>`<div class="score-row"><span style="color:${t.ink}">● ${t.name}</span><input id="score${i}" type="number" min="-9999" max="9999" value="${S.scores[i]}">${button('적용','applyScore',i,locked)}</div>`).join('')}${button('게임 초기화','reset','',locked,'danger')}</details>
<details id="bankDetails"><summary>Google Sheets 문제은행</summary><label for="apiUrl">구글시트 또는 Apps Script 주소</label><input id="apiUrl" type="url" placeholder="https://docs.google.com/spreadsheets/d/…/edit" value="${esc(api)}"><div class="row">${button(fetching?'불러오는 중…':'문제 새로고침','refresh','',fetching||locked||!board&&S.screen!=='opening')}</div><p>${esc(bankMessage|| (S.bankAt?'마지막 문제 반영: '+new Date(S.bankAt).toLocaleString('ko-KR'):'아직 시트에서 불러오지 않았습니다. 문제 새로고침을 눌러주세요.'))}</p><p>시트 수정 후 윷판 화면에서 문제 새로고침을 누르세요. 구글시트 주소는 링크로 열람 가능한 시트에서 사용할 수 있습니다.</p><p>사용여부가 FALSE이거나 없는 칸은 쉼터가 됩니다. 연결이 끊기면 마지막 문제를 계속 사용합니다.</p></details><p>연결 숫자는 행사 연출입니다. 실제 화상회의 접속 수를 측정하지 않습니다.</p>`;
openDetails.forEach(id=>{if($(id))$(id).open=true;});$('control').scrollTop=keep;if(locked||!authority)$('control').querySelectorAll('button').forEach(b=>{if(!['takeover','display','sound'].includes(b.dataset.action))b.disabled=true;});}
function render(){renderBoard();$('turnline').innerHTML=`이번 문제는 <span style="color:${TEAMS[S.selected].ink};border-bottom:4px solid ${TEAMS[S.selected].color}">${TEAMS[S.selected].name}</span>입니다!`;$('teamstrip').innerHTML=TEAMS.map((t,i)=>`<div class="teamflag ${S.selected===i?'current':''}" style="--team:${t.color};--team-ink:${t.ink}"><strong>● ${t.name}</strong><small>${t.count}개소 · ${S.scores[i]}점</small></div>`).join('');const full=['opening','bumper','finale'].includes(S.screen)||S.screen==='mission'&&S.card?.type==='golden';$('broadcastHeader').className=full?'hideheader':'';const key=JSON.stringify([S.screen,S.at,S.card?.id,S.outcome,S.cheerTarget,S.cheerWinner,S.chance,S.scores]);if(key!==lastScreen){lastScreen=key;$('screen').innerHTML=showHTML();}renderControl();updateClock();}
function updateClock(){const now=Date.now(),remaining=seconds();document.querySelectorAll('[data-timer]').forEach(el=>{el.textContent=remaining;el.classList.toggle('urgent',remaining<=10&&remaining>0);el.classList.toggle('last',remaining<=5&&remaining>0);el.style.setProperty('--progress',(S.timer?remaining/S.timer.duration*100:0)+'%');});if($('writePrompt'))$('writePrompt').textContent=remaining===0?'📸 정답판을 들어주세요!':remaining<=10?'📸 정답판을 들고 카메라를 바라봐주세요!':'✏️ 정답을 적어주세요!';if($('camcount'))$('camcount').textContent=Math.min(3,Math.floor((now-S.at)/1000)+1);if(S.screen==='opening'){const elapsed=now-S.at,count=Math.min(50,Math.max(10,Math.floor(elapsed/800)*10));if($('connectCount'))$('connectCount').innerHTML=count===50?'<b>50개소 연결 완료!</b>':`<b>${count}</b> / 50개소`;document.querySelectorAll('[data-home]').forEach(el=>el.classList.toggle('on',Number(el.dataset.home)<count/5));if($('onVillage'))$('onVillage').style.opacity=elapsed>4700?'1':'0';}if(S.screen==='finale'){if($('winnerView'))$('winnerView').hidden=now-S.at>5500;if($('finalThanks'))$('finalThanks').hidden=now-S.at<=5500;}let flash='';if(S.flash&&now<S.flashUntil)flash=S.flash;else if(now-S.turnAt<1400&&S.screen==='board')flash=TEAMS[S.selected].name+' TURN!';const holder=$('turnFlash');if(holder.dataset.message!==flash){holder.dataset.message=flash;holder.innerHTML=flash?`<div class="turnflash" style="--team:${TEAMS[S.selected].color}">${esc(flash)}</div>`:'';}}
function tick(){updateClock();if(!hasControl())return;const now=Date.now();if(S.timer?.running){const left=seconds();if(left!==lastClock){lastClock=left;if(left===10||left<=5&&left>0)tone('count');}if(left===0){endTimer();publish();}}
if(S.screen==='opening'&&now-S.at>=6500){setScreen('board');publish();}else if(S.screen==='camera'&&now>=S.cameraUntil){setScreen('question');publish();}else if(['standings','bumper'].includes(S.screen)&&now-S.at>=(S.screen==='standings'?5000:3500)){setScreen('board');publish();}}
function fit(){const rect=$('view').getBoundingClientRect();$('stage').style.transform=`scale(${Math.min(rect.width/1600,rect.height/900)})`;}
function claim(force=false){const lock=safeRead(KEYS.lock);if(!force&&lock&&Date.now()-lock.at<4500&&lock.owner!==owner){authority=false;return false;}safeWrite(KEYS.lock,{owner,at:Date.now()});authority=true;if(S.busy){S.busy=false;S.screen='board';S.notice='중단된 이동입니다. 실행취소 또는 위치 수정으로 이어가세요.';}return true;}
function boot(){mode=location.pathname.replace(/\/$/,'').endsWith('/display')||location.hash==='#display'?'display':'control';document.body.classList.toggle('display',mode==='display');owner=crypto.randomUUID?.()||String(Date.now())+Math.random();const saved=safeRead(KEYS.state);if(saved?.version===3&&Array.isArray(saved.players)&&saved.players.length===3)S=saved;else{const cache=safeRead(KEYS.bank);if(cache?.rows){try{S.bank=validateBank(cache.rows);S.bankAt=cache.at;}catch{}}}history=safeRead(KEYS.history)||[];try{channel=new BroadcastChannel('onmaeul-2026-v3');channel.onmessage=event=>{if(event.data?.kind==='hello'&&hasControl())channel.postMessage({kind:'state',state:S});if(event.data?.kind==='state'&&!authority&&event.data.state?.version===3){S=event.data.state;render();}};}catch{channel=null;}addEventListener('storage',event=>{if(event.key===KEYS.state&&!authority){try{S=JSON.parse(event.newValue);render();}catch{}}});if(mode==='control'){claim();if(authority)publish();}else channel?.postMessage({kind:'hello'});$('control').addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const {action,value}=b.dataset;if(action==='takeover'){if(confirm('기존 진행자 창 대신 이 창에서 이어서 조작할까요?')){claim(true);publish();}return;}if(action==='display'){const url=new URL(location.href);if(url.protocol==='file:')url.hash='display';else{url.pathname='/display';url.hash='';}displayWindow=window.open(url.href,'onmaeul-display');if(!displayWindow){apiMessage='팝업을 허용한 뒤 방송창 열기를 다시 눌러주세요.';renderControl();}else if(hasControl()&&S.screen==='opening'){S.at=Date.now();publish();}return;}if(action==='refresh'){refreshBank();return;}if(action==='applyPosition'){dispatch('position',$('positionInput').value);return;}if(action==='applyScore'){dispatch('score',value+':'+$('score'+value).value);return;}dispatch(action,value);});$('view').addEventListener('dblclick',()=>{try{if(!document.fullscreenElement)document.documentElement.requestFullscreen()?.catch(()=>{});else document.exitFullscreen()?.catch(()=>{});}catch{}});new ResizeObserver(fit).observe($('view'));render();fit();setInterval(tick,100);setInterval(()=>{if(authority&&hasControl())safeWrite(KEYS.lock,{owner,at:Date.now()});},1000);addEventListener('beforeunload',()=>{const lock=safeRead(KEYS.lock);if(authority&&lock?.owner===owner){try{localStorage.removeItem(KEYS.lock);}catch{}}});}

