/* Supabase 연결 계층. 공개 키만 사용하며 실제 쓰기 권한은 SQL의 RLS/RPC에서 검사합니다. */
let db, cloudVersion=-1, lease=false, leaseUntil=0, user=null, saving=false, queue=[], connected=false;
const rawNow=Date.now.bind(Date);let clockOffset=0;
Date.now=()=>rawNow()+clockOffset;
const originalControl=renderControl;
hasControl=()=>mode==='control'&&!!user&&connected&&lease&&Date.now()<leaseUntil;
saveHistory=()=>{};
publish=()=>{if(!hasControl())return;S.answerRevealed=S.screen==='answer';S.currentQuestionNumber=S.card?.id??null;render();queue.push({state:clone(S),history:clone(history)});drain();};
async function drain(){if(saving)return;saving=true;try{while(queue.length&&hasControl()){const item=queue.shift();const {data,error}=await db.rpc('save_game',{expected_version:cloudVersion,client_id:owner,next_state:item.state,next_history:item.history});if(error)throw error;cloudVersion=data;}}catch(e){queue=[];lease=false;authority=false;cloudNotice('저장하지 못했습니다. 연결과 조작권을 확인한 뒤 다시 이어받으세요. '+e.message);await loadCloud();}finally{saving=false;renderControl();}}
function cloudNotice(text){apiMessage=text;const el=$('cloudStatus');if(el)el.textContent=text;}
renderControl=function(){if(mode==='display')return;if(!user&&$('loginForm'))return;if(!user){$('control').innerHTML=`<h1>담당자 로그인</h1><p>등록된 행사 관리자만 조작할 수 있습니다.</p><form id="loginForm"><label>이메일</label><input name="email" type="email" required autocomplete="username"><label>비밀번호</label><input name="password" type="password" required autocomplete="current-password"><button>로그인</button></form><p id="cloudStatus">${esc(apiMessage)}</p>`;$('loginForm').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);const {error}=await db.auth.signInWithPassword({email:form.get('email'),password:form.get('password')});if(error)cloudNotice('로그인하지 못했습니다. 이메일과 비밀번호를 확인하세요.');else await authenticate();};return;}
 authority=hasControl();originalControl();$('control').insertAdjacentHTML('afterbegin',`<p id="cloudStatus">${esc(apiMessage|| (authority?'서버 연결 · 이 창에서 조작 중':'다른 화면의 진행 상황을 보고 있습니다.'))}</p><div class="row">${button('조작권 이어받기','takeover')}${button('로그아웃','logout')}</div>`);
 $('control').querySelectorAll('[data-action="takeover"]').forEach((b,i)=>{if(i)b.remove();});
 $('control').insertAdjacentHTML('beforeend',`<h2>문제 직접 선택</h2><select id="questionChoice">${S.bank.filter(c=>c.enabled).map(c=>`<option value="${c.id}">${c.id}번 ${esc(c.title)}</option>`).join('')}</select><div class="row">${button('선택 문제 띄우기','question')}${button('다음 문제','nextQuestion')}${button('문제 건너뛰기','complete')}${button('윷 던지기','random')}</div><h2>점수 + / −</h2>${TEAMS.map((t,i)=>`<div class="row">${t.name} ${S.scores[i]}점 ${button('+1','plus',i)}${button('−1','minus',i)}</div>`).join('')}`);
 if(!authority||S.busy)$('control').querySelectorAll('button').forEach(b=>{if(!['takeover','logout','display'].includes(b.dataset.action))b.disabled=true;});
};
async function loadCloud(){if(hasControl())return;const table=user?'game_private':'game_state';const {data,error}=await db.from(table).select('*').eq('id',1).maybeSingle();if(error)throw error;if(data?.state&&data.version>=cloudVersion&&!saving&&!queue.length){cloudVersion=data.version;S=data.state;history=user?(data.history||[]):[];render();}return data;}
async function authenticate(){const {data}=await db.auth.getUser();user=data.user;if(user){const {data:ok,error}=await db.rpc('is_game_admin');if(error||!ok){await db.auth.signOut();user=null;apiMessage='관리자 명단에 등록되지 않은 계정입니다.';}else await loadCloud();}renderControl();}
async function takeControl(){if(!user)return;if(lease&&hasControl())return;if(!confirm('이 창에서 진행을 이어받을까요? 다른 담당자 창의 조작은 중지됩니다.'))return;queue=[];await loadCloud();const {data,error}=await db.rpc('claim_game',{client_id:owner});if(error){cloudNotice(error.message);return;}lease=true;connected=true;leaseUntil=Date.parse(data);authority=true;if(cloudVersion<0){S=fresh();S.screen='board';cloudVersion=0;publish();}else if(S.busy){S.busy=false;S.screen='board';S.notice='중단된 이동입니다. 실행취소 또는 말 위치 수정으로 이어가세요.';publish();}renderControl();}
async function cloudBoot(){mode=['/admin','/control'].includes(location.pathname.replace(/\/$/,''))?'control':'display';document.body.classList.toggle('display',mode==='display');owner=crypto.randomUUID();S.screen='board';new ResizeObserver(fit).observe($('view'));render();fit();
 $('view').ondblclick=()=>document.documentElement.requestFullscreen?.().catch(()=>{});
 if(!CLOUD_CONFIG.url||!CLOUD_CONFIG.key){apiMessage='Supabase 설정이 필요합니다. README의 설정 순서를 따라 .env.local을 작성하고 다시 빌드하세요.';if(mode==='control'){$('control').innerHTML='<h1>서버 연결 설정</h1><p>'+apiMessage+'</p>';}else $('boardNote').textContent='행사 연결 준비 중';return;}
 db=supabase.createClient(CLOUD_CONFIG.url,CLOUD_CONFIG.key);const sent=rawNow();const time=await db.rpc('server_time');if(!time.error)clockOffset=Date.parse(time.data)-(sent+rawNow())/2;
 if(mode==='control')await authenticate();await loadCloud();
 const subscription=db.channel('onmaeul-public').on('postgres_changes',{event:'UPDATE',schema:'public',table:'game_state',filter:'id=eq.1'},async payload=>{if(!hasControl()&&!saving){if(user)await loadCloud();else if(payload.new.version>cloudVersion){cloudVersion=payload.new.version;S=payload.new.state;render();}}}).subscribe(async status=>{connected=status==='SUBSCRIBED';if(!connected){lease=false;authority=false;cloudNotice('서버 연결을 확인하고 있습니다. 마지막 화면은 유지됩니다.');}else{await loadCloud();cloudNotice('서버 연결 완료');}renderControl();});
 $('control').onclick=async event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const {action,value}=b.dataset;try{if(action==='display'){window.open('/game','onmaeul-display');return;}if(action==='logout'){lease=false;authority=false;queue=[];await db.auth.signOut();user=null;cloudVersion=-1;await loadCloud();renderControl();return;}if(action==='takeover'){await takeControl();return;}if(!hasControl())return;if(action==='refresh'){await refreshBank();return;}if(action==='applyPosition'){dispatch('position',$('positionInput').value);return;}if(action==='applyScore'){dispatch('score',value+':'+$('score'+value).value);return;}if(action==='plus'||action==='minus'){dispatch('score',value+':'+(S.scores[+value]+(action==='plus'?1:-1)));return;}if(action==='random'){dispatch('roll',1+crypto.getRandomValues(new Uint32Array(1))[0]%5);return;}if(action==='question'||action==='nextQuestion'){pushHistory();const bank=S.bank.filter(c=>c.enabled),card=action==='question'?bank.find(c=>c.id===+$('questionChoice').value):bank[(bank.findIndex(c=>c.id===S.card?.id)+1)%bank.length];if(!card)return;S.card=clone(card);S.timer=null;S.scored=false;S.outcome=null;setScreen('intro');publish();return;}dispatch(action,value);}catch(e){cloudNotice(e.message);}};
 setInterval(tick,100);setInterval(async()=>{try{if(lease){const {data,error}=await db.rpc('renew_game',{client_id:owner});if(error||!data){lease=false;authority=false;queue=[];}else leaseUntil=Date.parse(data);}if(!saving&&!queue.length)await loadCloud();renderControl();}catch{lease=false;authority=false;cloudNotice('인터넷 연결을 확인하세요. 저장이 확인될 때까지 조작이 잠깐 중지됩니다.');}},4000);
 db.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){user=null;lease=false;authority=false;queue=[];renderControl();}});
}
if(!globalThis.__TEST__)cloudBoot().catch(e=>{lease=false;authority=false;apiMessage='서버 연결 실패: '+e.message;if(mode==='control')$('control').innerHTML='<h1>연결 설정 확인</h1><p>'+esc(apiMessage)+'</p>';else $('boardNote').textContent='행사 연결 준비 중';});
