/* Existing Supabase tables, auth allowlist, leases and atomic saves are retained. */
let db,cloudVersion=-1,lease=false,leaseUntil=0,user=null,saving=false,queue=[],connected=false,loginPending=false;
const rawNow=Date.now.bind(Date);let clockOffset=0;Date.now=()=>rawNow()+clockOffset;
const originalControl=renderControl;
hasControl=()=>mode==='control'&&!!user&&connected&&lease&&Date.now()<leaseUntil;
saveHistory=()=>{};
publish=()=>{if(!hasControl())return;S.answerRevealed=S.screen==='answer';S.currentQuestionNumber=S.card?.id??null;render();queue.push({state:clone(S),history:clone(history)});return drain();};
async function drain(){if(saving)return;saving=true;try{while(queue.length&&hasControl()){const item=queue.shift();const {data,error}=await db.rpc('save_game',{expected_version:cloudVersion,client_id:owner,next_state:item.state,next_history:item.history});if(error)throw error;cloudVersion=data;}}catch(e){queue=[];lease=false;authority=false;cloudNotice('저장 실패: '+e.message+' · 조작권을 다시 이어받으세요.');await loadCloud();}finally{saving=false;renderControl();}}
function cloudNotice(text){apiMessage=text;const e=$('cloudStatus');if(e)e.textContent=text;}
renderControl=function(){if(mode==='display')return;if(!user){if($('loginForm'))return;controlKey='';$('control').innerHTML='<h1>담당자 로그인</h1><p>등록한 이메일과 비밀번호로 로그인하세요.</p><form id="loginForm"><label for="loginEmail">이메일</label><input id="loginEmail" name="email" type="email" autocomplete="username" required><label for="loginPassword">비밀번호</label><input id="loginPassword" name="password" type="password" autocomplete="current-password" required><button type="submit">로그인</button></form><p id="cloudStatus" role="status"></p><p><a href="/game" target="_blank">관람 화면 열기 ↗</a></p>';cloudNotice(apiMessage);$('loginForm').onsubmit=async e=>{e.preventDefault();if(loginPending)return;loginPending=true;const b=e.target.querySelector('button');b.disabled=true;b.textContent='확인 중…';try{if(!db)throw Error('서버 연결 중입니다. 잠시 후 다시 시도하세요.');const form=new FormData(e.target),{error}=await db.auth.signInWithPassword({email:String(form.get('email')).trim(),password:form.get('password')});if(error)throw Error(error.code==='invalid_credentials'?'이메일 또는 비밀번호가 맞지 않습니다.':error.message);await authenticate();}catch(e){cloudNotice(e.message);}finally{loginPending=false;if(b.isConnected){b.disabled=false;b.textContent='로그인';}}};return;}authority=hasControl();originalControl();};
async function loadCloud(){if(hasControl())return;const {data,error}=await db.from(user?'game_private':'game_state').select('*').eq('id',1).maybeSingle();if(error)throw error;if(data?.state&&data.version>=cloudVersion&&!saving&&!queue.length){cloudVersion=data.version;S=normalizeState(data.state);history=user?(data.history||[]).map(normalizeState):[];render();}return data;}
async function authenticate(){const {data,error}=await db.auth.getUser();if(error&&!data.user){user=null;renderControl();return;}const candidate=data.user;if(candidate){const {data:ok,error}=await db.rpc('is_game_admin');if(error)throw Error('관리자 권한 확인 실패: '+error.message);if(!ok){await db.auth.signOut();user=null;cloudNotice('관리자 명단에 등록되지 않은 계정입니다.');return;}user=candidate;controlKey='';await loadCloud();cloudNotice('로그인 완료 · 조작권 이어받기를 누르세요.');}renderControl();}
async function takeControl(){if(!user||hasControl())return;if(!confirm('이 창에서 게임을 조작할까요? 다른 담당자 창의 조작은 중지됩니다.'))return;queue=[];await loadCloud();const {data,error}=await db.rpc('claim_game',{client_id:owner});if(error)throw error;lease=true;connected=true;leaseUntil=Date.parse(data);authority=true;if(S.busy&&!S.flow){S.busy=false;S.dice=null;S.phase='ready';setScreen('board');S.notice='중단된 이동: 실행취소 또는 위치 수정으로 이어가세요.';}cloudNotice('이 창에서 조작 중 · 다른 컴퓨터에 실시간 반영됩니다.');publish();}
async function cloudBoot(){mode=['/admin','/control'].includes(location.pathname.replace(/\/$/,''))?'control':'display';document.body.classList.toggle('display',mode==='display');owner=crypto.randomUUID();new ResizeObserver(fit).observe($('view'));render();fit();$('view').ondblclick=()=>document.documentElement.requestFullscreen?.().catch(()=>{});
if(!CLOUD_CONFIG.url||!CLOUD_CONFIG.key){cloudNotice('서버 연결 환경변수 설정이 필요합니다.');return;}db=supabase.createClient(CLOUD_CONFIG.url,CLOUD_CONFIG.key);const sent=rawNow(),time=await db.rpc('server_time');if(!time.error)clockOffset=Date.parse(time.data)-(sent+rawNow())/2;if(mode==='control')await authenticate();await loadCloud();
db.channel('onmaeul-public').on('postgres_changes',{event:'UPDATE',schema:'public',table:'game_state',filter:'id=eq.1'},async payload=>{try{if(!hasControl()&&!saving&&!queue.length){if(user)await loadCloud();else if(payload.new.version>cloudVersion){cloudVersion=payload.new.version;S=normalizeState(payload.new.state);render();}}}catch(e){cloudNotice(e.message);}}).subscribe(async status=>{connected=status==='SUBSCRIBED';if(!connected){lease=false;authority=false;cloudNotice('연결 확인 중 · 마지막 진행 상황은 유지됩니다.');}else{try{await loadCloud();cloudNotice(user?'서버 연결 완료 · 조작권 이어받기를 누르세요.':'서버 연결 완료');}catch(e){cloudNotice(e.message);}}renderControl();});
$('control').onclick=async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;let {action,value}=b.dataset;try{if(action==='localAudio'){enableLocalSound();return;}if(action==='logout'){lease=false;authority=false;queue=[];await db.auth.signOut();user=null;cloudVersion=-1;controlKey='';await loadCloud();renderControl();return;}if(action==='takeover'){await takeControl();return;}if(!hasControl())return;if(action==='refresh'){await refreshBank();return;}const input={position:'positionInput',question:'questionChoice',points:'pointsInput',turns:'turnsInput'}[action];if(input)value=$(input).value;dispatch(action,value);}catch(e){cloudNotice(e.message);}};
setInterval(tick,100);setInterval(async()=>{try{if(lease){const {data,error}=await db.rpc('renew_game',{client_id:owner});if(error||!data){lease=false;authority=false;queue=[];cloudNotice('조작권이 종료되었습니다. 다시 이어받으세요.');}else leaseUntil=Date.parse(data);}if(!saving&&!queue.length)await loadCloud();renderControl();}catch(e){lease=false;authority=false;cloudNotice('서버 연결 확인: '+e.message);}},4000);
db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){user=null;lease=false;authority=false;queue=[];controlKey='';renderControl();}});
}
if(!globalThis.__TEST__)cloudBoot().catch(e=>{lease=false;authority=false;cloudNotice('연결 실패: '+e.message);});
