const fs=require('fs'),vm=require('vm'),assert=require('assert');const html=fs.readFileSync(require('path').join(__dirname,'dist/index.html'),'utf8');const js='const DEFAULT_BANK='+fs.readFileSync(require('path').join(__dirname,'board-data.json'),'utf8')+';'+fs.readFileSync(require('path').join(__dirname,'app.js'),'utf8');const elements={};const el=id=>elements[id]??={value:'',textContent:'',innerHTML:'',hidden:false,classList:{toggle(){}},style:{setProperty(){}},dataset:{},querySelectorAll:()=>[]};const context={__TEST__:true,assert,console,setTimeout:f=>{f();return 0},clearTimeout(){},confirm:()=>true,document:{getElementById:el,querySelectorAll:()=>[]},localStorage:{getItem:()=>null,setItem(){}},Date};vm.createContext(context);vm.runInContext(js,context);
(async()=>{await vm.runInContext(`(async()=>{
authority=true;hasControl=()=>true;render=()=>{};renderControl=()=>{};updateClock=()=>{};tone=()=>{};publish=()=>{S.revision++};
const sample=validateBank(DEFAULT_BANK);assert.equal(sample.length,29);assert.equal(new Set(sample.map(c=>c.id)).size,29);assert.equal(sample.filter(c=>c.id===27)[0].type,'golden');
let err=false;try{validateBank([DEFAULT_BANK[0],DEFAULT_BANK[0]])}catch{err=true}assert(err);
assert.equal(validateBank([{'칸번호':3,'유형':'추억퀴즈','제목':'그 시절','문제':'질문','보기1':'가','보기2':'나','보기3':'다','보기4':'라','정답':2,'제한시간':40,'사용여부':true}])[0].answer,'나');
assert.equal(validateBank([{'칸번호':4,'유형':'노래','제목':'함께 노래','미션내용':'불러요','제한시간':30,'사용여부':'TRUE'}])[0].choices.length,0);
assert.equal(validateBank([{...DEFAULT_BANK[0],enabled:false}])[0].enabled,false);
const route=(path,n,r='shortcut')=>{const p={path:path.slice()};for(let i=0;i<n;i++)p.path.push(nextStep(p,i===0,r));return p.path};
assert.deepEqual(route(['S'],3),['S',12,11,10]);assert.deepEqual(route([7],4),[7,26,27,28,19]);assert.deepEqual(route([7],2,'outer'),[7,6,5]);assert.deepEqual(route([1],4),[1,25,27,29,13]);assert.deepEqual(route([1],2,'outer'),[1,24,23]);assert.deepEqual(route([26,27],2),[26,27,29,13]);assert.deepEqual(route([26,27],2,'outer'),[26,27,28,19]);assert.deepEqual(route([14],2),[14,13,'F']);for(let n=1;n<=29;n++)assert.equal(position({path:canonical(n)}),n);
S=fresh();S.screen='board';await roll(2);assert.equal(position(S.players[0]),11);assert.equal(S.screen,'intro');openContent();assert.equal(S.screen,'question');assert.equal(seconds(),20);dispatch('answer');assert.equal(S.screen,'question');timerAction('pause');assert.equal(S.timer.running,false);timerAction('add');assert(seconds()>=29);timerAction('restart');assert.equal(S.timer.running,true);timerAction('end');assert.equal(S.screen,'camera');assert.equal(S.timer.ended,true);S.cameraUntil=Date.now()-1;tick();assert.equal(S.screen,'question');dispatch('answer');assert.equal(S.screen,'answer');dispatch('good');assert.equal(S.scores[0],1);dispatch('good');assert.equal(S.scores[0],1);dispatch('undo');assert.equal(S.scores[0],0);finishContent();dispatch('next');assert.equal(S.selected,1);dispatch('next');assert.equal(S.selected,2);dispatch('next');assert.equal(S.selected,0);
S=fresh();S.screen='board';history=[];S.players[1].path=canonical(11);await roll(2);assert.equal(position(S.players[1]),'S');assert.equal(S.extra,true);dispatch('undo');assert.equal(position(S.players[1]),11);assert.equal(position(S.players[0]),'S');
S=fresh();S.screen='board';await roll(4);assert(S.extra);dispatch('undo');assert.equal(position(S.players[0]),'S');
S=fresh();S.screen='board';S.players[0].path=canonical(27);await roll(-1,true);assert.equal(position(S.players[0]),26);dispatch('position','29');assert.equal(position(S.players[0]),29);dispatch('undo');assert.equal(position(S.players[0]),26);
S=fresh();S.screen='board';startCheer();assert.equal(seconds(),10);dispatch('cheerwinner','2');assert.equal(S.scores[2],0);timerAction('end');dispatch('cheerwinner','2');assert.equal(S.scores[2],2);dispatch('cheerwinner','2');assert.equal(S.scores[2],2);dispatch('undo');assert.equal(S.scores[2],0);
S=fresh();S.card=clone(DEFAULT_BANK.find(c=>c.id===7));S.screen='chance';revealChance();assert.equal(S.scores[0],2);revealChance();assert.equal(S.scores[0],2);S.card={prompt:'[한번더] 더 해요'};S.chanceApplied=false;revealChance();assert.equal(S.extra,true);assert.equal(parseChance({prompt:'[보너스] 문제'}).type,'bonus');
S=fresh();S.card=clone(DEFAULT_BANK.find(c=>c.id===27));S.screen='mission';applyScore(true);assert.deepEqual(S.scores,[1,1,1]);applyScore(true);assert.deepEqual(S.scores,[1,1,1]);
S=fresh();S.screen='standings';S.at=Date.now()-5100;tick();assert.equal(S.screen,'board');S.screen='opening';S.at=Date.now()-6600;tick();assert.equal(S.screen,'board');S.scores=[2,5,5];dispatch('finale');assert(showHTML().includes('공동 우승'));assert(showHTML().includes('관장팀'));dispatch('reset');assert.deepEqual(S.scores,[0,0,0]);
for(const screen of ['opening','board','intro','question','camera','answer','mission','chance','cheer','standings','bumper','finale']){S=fresh();S.screen=screen;S.card=clone(DEFAULT_BANK[0]);if(screen==='mission')S.card=clone(DEFAULT_BANK.find(c=>c.id===27));assert.equal(typeof showHTML(),'string');}
assert(!showHTML().includes('data-action'));
})()`,context);console.log('PASS: 29-cell bank validation, Korean Sheets schema, all routes, manual shortcut, timer stages, no automatic answer, capture/extra, undo, scoring idempotency, cheer +2, golden all-team score, finale ties, 12 screens.');})().catch(e=>{console.error(e);process.exitCode=1});
