const fs=require('fs'),vm=require('vm'),assert=require('assert');let now=100000;class Clock extends Date{static now(){return now}}const context={assert,console,Date:Clock,confirm:()=>true,setTimeout,clearTimeout,crypto:require('crypto').webcrypto,document:{getElementById:()=>({value:'8'}),querySelectorAll:()=>[]},localStorage:{getItem:()=>null,setItem(){}}};vm.createContext(context);vm.runInContext('const DEFAULT_BANK='+fs.readFileSync(__dirname+'/board-data.json','utf8')+';'+fs.readFileSync(__dirname+'/app.js','utf8'),context);context.advance=n=>{now+=n};vm.runInContext(`
authority=true;hasControl=()=>true;render=()=>{};renderControl=()=>{};updateClock=()=>{};tone=()=>{};publish=()=>{};
const step=()=>{advance(Math.max(0,S.flow.due-Date.now())+1);tick();};
S=fresh();S.scores=[10,20,30];const positions=JSON.stringify(S.players);for(let i=0;i<3;i++)dispatch('scoreDelta',i+':5');assert.deepEqual(S.scores,[15,25,35]);assert.equal(JSON.stringify(S.players),positions);assert.equal(S.completed,0);assert.deepEqual(TEAMS.map(t=>t.name),['동대문구청팀','복지관팀','동대문구지회팀']);
assert.equal(Object.keys(coords).length,30);const p={path:['S']};for(let n=1;n<=29;n++){p.path.push(nextStep(p));assert.equal(position(p),n)}assert.equal(nextStep(p),'S');
S=fresh();assert.equal(S.selected,1);dispatch('start');for(let i=0;i<5;i++)step();assert.equal(S.screen,'board');assert.equal(S.selected,1);
dispatch('dieSelect',4);assert.equal(position(S.players[1]),'S');dispatch('revealDice');assert.equal(S.dice.value,4);assert.equal(S.flow.kind,'move');pauseAll();const frozen=JSON.stringify(S.players),due=S.flow.due;advance(20000);tick();assert.equal(JSON.stringify(S.players),frozen);resumeAll();assert.equal(S.flow.due,due+20000);while(S.busy)step();assert.equal(position(S.players[1]),4);step();assert.equal(S.screen,'intro');assert.equal(S.flow,null);dispatch('open');assert.equal(S.screen,'mission');assert.equal(seconds(),20);
pauseAll();advance(9000);assert.equal(seconds(),20);timerAction('restart');assert.equal(seconds(),20);resumeAll();advance(20001);tick();assert(S.timer.ended);assert.equal(S.screen,'mission');
applyScore(true);assert.equal(S.scores[1],15);assert.equal(S.successes[1],1);applyScore(true);assert.equal(S.scores[1],15);pauseAll();advance(10000);tick();assert.equal(S.screen,'mission');resumeAll();step();assert.equal(S.screen,'turn');pauseAll();advance(10000);tick();assert.equal(S.selected,1);resumeAll();step();assert.equal(S.selected,0);assert.equal(S.screen,'board');
S.roundOpen=true;finishContent();step();assert.equal(S.selected,2);S.roundOpen=true;finishContent();step();assert.equal(S.selected,1);
S=fresh();S.screen='board';S.players[1].path=canonical(28);roll(4);while(S.busy)step();assert.equal(position(S.players[1]),2);assert.equal(position(S.players[0]),'S');step();dispatch('open');assert.equal(S.screen,'question');advance(20001);tick();assert.equal(S.screen,'question');dispatch('camera');assert.equal(S.screen,'camera');dispatch('answer');assert.equal(S.screen,'answer');applyScore(false);assert.equal(S.scores[1],0);assert.equal(S.successes[1],0);

// Double movement preserves the physical die face and consumes the toggle once.
for(const value of [1,2,3,4,5,6]){S=fresh();S.screen='board';dispatch('dieSelect',value);dispatch('dieDouble');dispatch('revealDice');assert.equal(S.dice.value,value);assert.equal(S.dice.steps,value*2);assert.equal(S.dice.multiplier,2);assert.equal(S.dieDouble,false);const moving=S.move.left;dispatch('revealDice');assert.equal(S.move.left,moving);while(S.busy)step();assert.equal(position(S.players[1]),value*2);assert.equal(S.scores[1],0);}
S=fresh();S.screen='board';S.players[1].path=canonical(28);dispatch('dieSelect',6);dispatch('dieDouble');dispatch('revealDice');pauseAll();const doubleLeft=S.move.left;advance(5000);tick();assert.equal(S.move.left,doubleLeft);resumeAll();while(S.busy)step();assert.equal(position(S.players[1]),10);
S=fresh();S.screen='board';dispatch('dieDouble');dispatch('dieDouble');roll(2);assert.equal(S.move.left,2);assert.equal(normalizeState({}).dieDouble,false);
S=fresh();S.screen='board';dispatch('dieDouble');S.paused=true;dispatch('revealDice');assert.equal(S.dieDouble,true);assert.equal(S.dice,null);
for(const [type,points] of [['chuseok',10],['town',10],['chance',20],['cheer',20],['song',15],['mission',15]])assert.equal(pointsFor({type}),points);
S=fresh();S.selected=0;S.card={id:1,type:'chuseok'};S.screen='answer';S.successes=[7,0,0];S.roundOpen=true;applyScore(true);assert.equal(S.successes[0],8);assert(!S.communityAchieved);dispatch('replayAnswer');applyScore(true);assert.equal(S.successes[0],8);assert.equal(S.scores[0],10);
S.scores=[100,999,70];S.successes=[8,7,9];beginFinale();assert.equal(S.screen,'finalWait');dispatch('finalReveal');assert.equal(S.finaleIndex,4);assert(showHTML().includes('우리 모두가 한 팀'));assert(showHTML().includes('999'));assert.equal(ranks()[0].i,1);
const old={...fresh(),communityVersion:undefined,scores:[100,120,80],bank:clone(DEFAULT_BANK)};const migrated=normalizeState(old);assert.deepEqual(migrated.scores,old.scores);assert.deepEqual(migrated.bank.map(c=>c.question),old.bank.map(c=>c.question));assert.deepEqual(migrated.successes,[0,0,0]);assert.equal(migrated.selected,1);
S=fresh();S.screen='board';roll(3);step();const at=position(S.players[1]);pauseAll();dispatch('nextStage');assert.notEqual(position(S.players[1]),at);assert(S.paused);dispatch('previous');assert.equal(position(S.players[1]),at);assert(S.paused);
S=fresh();S.completed=28;S.roundOpen=true;finishContent();assert.equal(S.screen,'finalWait');assert.equal(S.completed,29);
for(const screen of ['start','opening','board','turn','intro','question','camera','answer','mission','chance','finale']){S=fresh();S.screen=screen;S.card=clone(DEFAULT_BANK[0]);assert.equal(typeof showHTML(),'string');assert(!showHTML().includes('data-action'));}
`,context);console.log('PASS: physical dice, sequential moves, all-phase pause/resume, step rewind, automatic team order, sheet-configurable points, raw-score MVP, no duplicate rewards, ranked finale, legacy data preservation.');
